---
# Here belong all actions like service-restart,
# config-file loads, etc. that will be started
# if a change on a task was made


- name: start elasticsearch
  service: 
    name: elasticsearch
    state: started

- name: stop elasticsearch
  service: 
    name: elasticsearch
    state: stopped

- name: restart elasticsearch
  service: 
    name: elasticsearch
    state: restarted

...