---
- name: Install EPEL Release
  dnf:
    name: epel-release

- name: Configure Elasticsearch repo
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644

...
